version: '3.8'

services:
  astrbot:
    image: soulter/astrbot:latest
    container_name: astrbot
    ports:
      - "6185:6185"
      - "6195:6195"
      - "6199:6199"
      - "6196:6196"
      - "11451:11451"
    volumes:
      - ./data:/AstrBot/data
    networks:
      - astrbot_network

  napcat:
    environment:
      - NAPCAT_UID=${NAPCAT_UID}
      - NAPCAT_GID=${NAPCAT_GID}
      - MODE=astrbot
    ports:
      - 3000:3000
      - 3001:3001
      - 6099:6099
    container_name: napcat
    network_mode: bridge
    restart: always
    image: mlikiowa/napcat-docker:latest
    volumes:
      - ./napcat:/app/napcat/config
      - ./ntqq:/app/.config/QQ
    networks:
      - astrbot_network
    mac_address: "02:42:ac:11:00:02"

networks:
  astrbot_network:
    driver: bridge