name: Docker

on:
  workflow_dispatch:

jobs:
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get artifacts
        run: |
          bash get_artifacts.sh ${{ secrets.GITHUB_TOKEN }} $(curl "https://api.github.com/repos/NapNeko/NapCatQQ/releases/latest" | jq -r '.tag_name')
          ls -lh
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Hub login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login \
            --username "${DOCKER_USERNAME}" \
            --password-stdin
      - name: Run buildx and push
        env:
          DOCKER_REPO: mlikiowa/napcat-docker
          GITHUB_REPO: NapNeko/NapCatQQ
        run: |
          TAG=$(curl "https://api.github.com/repos/NapNeko/NapCatQQ/releases/latest" | jq -r '.tag_name')
          docker buildx build \
            --build-arg LINK=$LINK \
            --output "type=image,push=true" \
            --platform linux/amd64,linux/arm64 \
            --tag ${DOCKER_REPO}:$TAG \
            --tag ${DOCKER_REPO}:latest \
            --file ./Dockerfile \
            ./docker
      - name: Docker Hub logout
        if: always()
        run: docker logout